//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorSkin.Models
{
    using DoctorSkin.Models;
    using DoctorSkin.Models.Role;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Web.UI.WebControls;

    public partial class DoctorSkinEntities : DbContext
    {
        public DoctorSkinEntities()
            : base("name=myDatabase")
        {
        }

        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}

        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }

        public virtual DbSet<BlogDetails> BlogDetails { get; set; }
        public virtual DbSet<BlogTypes> BlogType { get; set; }

        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<Medias> Medias { get; set; }

        public virtual DbSet<Services> Services { get; set; }

        public virtual DbSet<Bills> Bills { get; set; }
        public virtual DbSet<Feedbacks> Feedbacks { get; set; }

        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<RepFeedbacks> RepFeedbacks { get; set; }

        public System.Data.Entity.DbSet<DoctorSkin.Models.ServicesDetails> ServicesDetails { get; set; }

        public System.Data.Entity.DbSet<DoctorSkin.Models.ViewModel.ProductsViewModel> ProductsViewModels { get; set; }

        public System.Data.Entity.DbSet<DoctorSkin.Models.ViewModel.UserFeedBackViewModel> UserFeedBackViewModels { get; set; }

        public System.Data.Entity.DbSet<DoctorSkin.Models.Wishlists> Wishlists { get; set; }

        public System.Data.Entity.DbSet<DoctorSkin.Models.Carts> Carts { get; set; }

        public System.Data.Entity.DbSet<DoctorSkin.Models.Booking> Bookings { get; set; }
        public System.Data.Entity.DbSet<DoctorSkin.Models.Forgots> Forgots { get; set; }

        public System.Data.Entity.DbSet<DoctorSkin.Models.Vouchers> Vouchers { get; set; }

        public System.Data.Entity.DbSet<DoctorSkin.Models.Role.UserRoles> Roles { get; set; }
        public System.Data.Entity.DbSet<DoctorSkin.Models.Role.RoleMasters> RoleMasters { get; set; }
        public System.Data.Entity.DbSet<DoctorSkin.Models.Role.UserRolesMappings> UserRolesMappings { get; set; }

        public System.Data.Entity.DbSet<DoctorSkin.Models.Medicines> Medicines { get; set; }

        public System.Data.Entity.DbSet<DoctorSkin.Models.ViewModel.MedicinesModel> MedicinesModels { get; set; }
        public System.Data.Entity.DbSet<DoctorSkin.Models.Banners> Banners { get; set; }

        public System.Data.Entity.DbSet<DoctorSkin.Models.Patients> Patients { get; set; }

        public System.Data.Entity.DbSet<DoctorSkin.Models.Questions> Questions { get; set; }
    }
}
